"""initial

Revision ID: 49deb493d7f2
Revises: 
Create Date: 2025-09-22 15:37:57.193360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49deb493d7f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex_enum'), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('activity_multiplier', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_level_enum'), nullable=True),
    sa.Column('goal', sa.Enum('lose', 'maintain', 'gain', name='goal_enum'), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('google_tokens', sa.Text(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('avg_bpm', sa.Float(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('fitness_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('avg_bpm', sa.Float(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_data_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitness_data_user_id'), ['user_id'], unique=False)

    op.create_table('lifestyle_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifestyle_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifestyle_points_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifestyle_points_user_id'), ['user_id'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_user_id'))
        batch_op.drop_index(batch_op.f('ix_meals_date'))

    op.drop_table('meals')
    with op.batch_alter_table('lifestyle_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifestyle_points_user_id'))
        batch_op.drop_index(batch_op.f('ix_lifestyle_points_date'))

    op.drop_table('lifestyle_points')
    with op.batch_alter_table('fitness_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_fitness_data_date'))

    op.drop_table('fitness_data')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
