"""Add activities tables

Revision ID: e687d391ace8
Revises: 49deb493d7f2
Create Date: 2025-09-22 22:20:43.878952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e687d391ace8'
down_revision = '49deb493d7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('activity_type', sa.String(length=128), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('activity_level',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('steps')
        batch_op.drop_column('avg_bpm')
        batch_op.drop_column('target_calories')
        batch_op.drop_column('sleep_minutes')
        batch_op.drop_column('goal')
        batch_op.drop_column('raw_payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_payload', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('sleep_minutes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('target_calories', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('avg_bpm', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.INTEGER(), nullable=True))
        batch_op.alter_column('activity_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_date'))

    op.drop_table('activities')
    # ### end Alembic commands ###
