"""Add activities tables

Revision ID: eef466759785
Revises: e687d391ace8
Create Date: 2025-09-22 23:15:43.868611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef466759785'
down_revision = 'e687d391ace8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_hours', sa.Float(), nullable=True))
        batch_op.drop_column('sleep_minutes')

    with op.batch_alter_table('lifestyle_points', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('lifestyle_points', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('fitness_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_minutes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('sleep_hours')

    # ### end Alembic commands ###
